/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CoachRouteImport } from './routes/coach'
import { Route as LessonRouteRouteImport } from './routes/lesson/route'
import { Route as QuestionRouteImport } from './routes/question'
import { Route as ReviewRouteImport } from './routes/review'
import { Route as ScheduleRouteImport } from './routes/schedule'
import { Route as LessonLessonIdRouteImport } from './routes/lesson/$lessonId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachRoute = CoachRouteImport.update({
  id: '/coach',
  path: '/coach',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonRouteRoute = LessonRouteRouteImport.update({
  id: '/lesson',
  path: '/lesson',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestionRoute = QuestionRouteImport.update({
  id: '/question',
  path: '/question',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewRoute = ReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduleRoute = ScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonLessonIdRoute = LessonLessonIdRouteImport.update({
  id: '/$lessonId',
  path: '/$lessonId',
  getParentRoute: () => LessonRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/lesson': typeof LessonRouteRouteWithChildren
  '/coach': typeof CoachRoute
  '/question': typeof QuestionRoute
  '/review': typeof ReviewRoute
  '/schedule': typeof ScheduleRoute
  '/lesson/$lessonId': typeof LessonLessonIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/lesson': typeof LessonRouteRouteWithChildren
  '/coach': typeof CoachRoute
  '/question': typeof QuestionRoute
  '/review': typeof ReviewRoute
  '/schedule': typeof ScheduleRoute
  '/lesson/$lessonId': typeof LessonLessonIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/lesson': typeof LessonRouteRouteWithChildren
  '/coach': typeof CoachRoute
  '/question': typeof QuestionRoute
  '/review': typeof ReviewRoute
  '/schedule': typeof ScheduleRoute
  '/lesson/$lessonId': typeof LessonLessonIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/lesson'
    | '/coach'
    | '/question'
    | '/review'
    | '/schedule'
    | '/lesson/$lessonId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/lesson'
    | '/coach'
    | '/question'
    | '/review'
    | '/schedule'
    | '/lesson/$lessonId'
  id:
    | '__root__'
    | '/'
    | '/lesson'
    | '/coach'
    | '/question'
    | '/review'
    | '/schedule'
    | '/lesson/$lessonId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LessonRouteRoute: typeof LessonRouteRouteWithChildren
  CoachRoute: typeof CoachRoute
  QuestionRoute: typeof QuestionRoute
  ReviewRoute: typeof ReviewRoute
  ScheduleRoute: typeof ScheduleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach': {
      id: '/coach'
      path: '/coach'
      fullPath: '/coach'
      preLoaderRoute: typeof CoachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lesson': {
      id: '/lesson'
      path: '/lesson'
      fullPath: '/lesson'
      preLoaderRoute: typeof LessonRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/question': {
      id: '/question'
      path: '/question'
      fullPath: '/question'
      preLoaderRoute: typeof QuestionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review': {
      id: '/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule': {
      id: '/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof ScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lesson/$lessonId': {
      id: '/lesson/$lessonId'
      path: '/$lessonId'
      fullPath: '/lesson/$lessonId'
      preLoaderRoute: typeof LessonLessonIdRouteImport
      parentRoute: typeof LessonRouteRoute
    }
  }
}

interface LessonRouteRouteChildren {
  LessonLessonIdRoute: typeof LessonLessonIdRoute
}

const LessonRouteRouteChildren: LessonRouteRouteChildren = {
  LessonLessonIdRoute: LessonLessonIdRoute,
}

const LessonRouteRouteWithChildren = LessonRouteRoute._addFileChildren(
  LessonRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LessonRouteRoute: LessonRouteRouteWithChildren,
  CoachRoute: CoachRoute,
  QuestionRoute: QuestionRoute,
  ReviewRoute: ReviewRoute,
  ScheduleRoute: ScheduleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
